### ISSUE TITLE
Does migration work against an on premise TFS?

### ISSUE THREAD

**Issue by johanclasson** [johanclasson/MigrationTools#2]
I've tested migration against VSTS, but not an on premise TFS.

**Comment by jespersh** [comment]
I tested it and I had to modify a bit and there was another two gotchas. 
 * The ```$Product Backlog Item``` only exists in a scrum workflow.
 * github specific I had to run first: ```[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12;```

The only line I had to change was this:
```$url = "$TfsCollectionUrl/$TfsProject/_apis/wit/workitems/$($id)?bypassRules=true&api-version=1.0"```
to this:
```$url = "$TfsCollectionUrl/_apis/wit/workitems/$($id)?bypassRules=true&api-version=1.0"```
Just omit the $TfsProject or it'll 404

**Comment by johanclasson** [comment]
Nice. Thanks for the feedback! 😃 

I wonder why I included the project in the url in the first place, but I do remember that when I ran this script in 2016 it worked.

The [docs say](https://www.visualstudio.com/en-us/docs/integrate/api/wit/work-items#updateafield) that the project should not be there. And the version is still 1.0. Very strange.

**Comment by jespersh** [comment]
You're welcome and thanks for the script. It saved a lot of manual work.
