### ISSUE TITLE
Connection was closed unexpectedly at line 50

### ISSUE THREAD

**Issue by louistsui** [johanclasson/MigrationTools#7]
Hi Johan,

I came across your PowerShell script whist looking for ways to do one time transfer Github issues to VSTS. The script ran but failed with following output:

    Invoke-WebRequest : The request was aborted: The connection was closed unexpectedly.
    At Convert-Issues.ps1:50 char:19
    +         $result = Invoke-WebRequest -Uri $Url -Headers $Headers
    +                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
        + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

Any idea what I have done wrong?

Many thanks in advance

Louis

**Comment by louistsui** [comment]
Looks like my $GitHubIssuesUrl did not start with `https://api.github.com/repos` hence connect failed.

My bad, sorry

**Comment by johanclasson** [comment]
Great that you managed to sort it out! :)
