### ISSUE TITLE
Line 200 hardcoded

### ISSUE THREAD

**Issue by louistsui** [johanclasson/MigrationTools#8]
Hi Johan,

Line 200:

    $url = "https://nethouse-solutions.visualstudio.com/_apis/wit/workitems/$($id)?bypassRules=true&api-version=1.0"

Should change to:

    $url = "$TfsCollectionUrl/_apis/wit/workitems/$($id)?bypassRules=true&api-version=1.0"

??

**Comment by johanclasson** [comment]
Oups. Thanks for telling me!
